services:
  - type: pserv
    name: mongodb
    env: docker
    plan: starter
    region: oregon
    disk:
      name: mongo-data
      mountPath: /data/db
      sizeGB: 10
    envVars:
      - key: MONGO_INITDB_ROOT_USERNAME
      - key: MONGO_INITDB_ROOT_PASSWORD
      - key: MONGO_INITDB_DATABASE
    autoDeploy: true
